apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana #nome do pode
  labels:
    app: grafana #colocar na service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-enterprise #imagem docker
          imagePullPolicy: IfNotPresent