apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pod #nome do pode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config-volume
            - mountPath: /prometheus
              name: prometheus-vol
      initContainers:
        - name: prometheus-data
          image: ubuntu
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: prometheus-vol
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: configmaps
        - name: prometheus-vol
          persistentVolumeClaim:
            claimName: vol-prometheus
      restartPolicy: Always
      