apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistente-vol-prometheus
spec:
  storageClassName: prometheus
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kdi/git/AFOARQ3/curso/projetoFinal/teste
