apiVersion: v1
kind: Service
metadata:
  name: service-prometheus #nome do pode
spec:
  selector:
    app: prometheus  #passar no pod
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
